services:
  app:
    build:
      context: ./php
    container_name: statamic_app
    volumes:
      - ./app:/app
    working_dir: /app
    user: "1000:33"
    networks:
      - statamic_net

  web:
    image: nginx:stable-alpine
    container_name: statamic_web
    ports:
      - "8081:80"
    volumes:
      - ./app:/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - statamic_net

networks:
  statamic_net:
    driver: bridge