services:
  app:
    container_name: project-name
    build:
      context: ./php
    volumes:
      - ./app:/app
    working_dir: /app
    user: "1000:33"

  web:
    image: nginx:stable-alpine
    container_name: project-name_webserver
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app