services:
  app:
    build:
      context: ./php
    container_name: flow-cms-statamic
    volumes:
      - ./app:/app
    working_dir: /app
    user: "1000:33"
    networks:
      - flow_net

  web:
    image: nginx:stable-alpine
    container_name: flow-cms-webserver
    ports:
      - "8081:80"
    volumes:
      - ./app:/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - flow_net

networks:
  flow_net:
    external: true